[package]
name = "blockchain"
version = "0.1.0"
authors = ["Ben Windsor <benjaminwindsor@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.16"